#!/usr/bin/env bash
# Post-process Reppo write intents left by Claude (sandbox blocks outbound network).
# Reads .pending-reppo/*.json, runs a --dry-run preflight, then the real write.
# Appends results to .outputs/reppo-trading-agent.md for the digest step.
#
# Env:
#   REPPO_PRIVATE_KEY     required for any write (script skips writes if unset)
#   REPPO_DRY_RUN_ONLY    if "true", run the dry-run preflight but skip real writes
set -euo pipefail

PENDING_DIR=".pending-reppo"
RESULTS_FILE=".outputs/reppo-trading-agent.md"
DRY_RUN_ONLY="${REPPO_DRY_RUN_ONLY:-false}"

if [ ! -d "$PENDING_DIR" ] || [ -z "$(ls -A "$PENDING_DIR"/*.json 2>/dev/null || true)" ]; then
  echo "reppo-postprocess: no pending intents"
  exit 0
fi

if [ -z "${REPPO_PRIVATE_KEY:-}" ]; then
  echo "reppo-postprocess: REPPO_PRIVATE_KEY not set, skipping all writes"
  mkdir -p .outputs
  {
    echo ""
    echo "## Execution Results"
    echo ""
    echo "_postprocess-reppo.sh skipped ALL writes: REPPO_PRIVATE_KEY is not set. No intents were executed on-chain._"
  } >> ".outputs/reppo-trading-agent.md"
  exit 0
fi

if ! command -v reppo >/dev/null 2>&1; then
  npm i -g @reppo/cli >/dev/null 2>&1 || {
    echo "reppo-postprocess: CLI missing"
    mkdir -p .outputs
    {
      echo ""
      echo "## Execution Results"
      echo ""
      echo "_postprocess-reppo.sh could not run: Reppo CLI unavailable. Pending intents were NOT executed._"
    } >> ".outputs/reppo-trading-agent.md"
    exit 0
  }
fi

mkdir -p .outputs .reppo-cache
{
  echo ""
  echo "## Execution Results"
  echo ""
  echo "_Generated by postprocess-reppo.sh ($(date -u +%FT%TZ)). dry_run_only=${DRY_RUN_ONLY}_"
  echo ""
} >> "$RESULTS_FILE"

# Build the CLI argument list for an intent file. Args: file. Echoes args.
# Returns 1 if the command is unknown or any field is malformed. Validating
# fields here keeps the later unquoted `$args` expansion safe (every word is
# then a controlled flag, an id token, or a positive integer — no spaces).
# `id` accepts Reppo's integer datanet/pod ids as well as hex/hyphenated ids.
build_args() {
  local f="$1" cmd id='^[A-Za-z0-9_-]+$'
  cmd="$(jq -r '.cmd' "$f")"
  case "$cmd" in
    mint-pod)
      local datanet
      datanet="$(jq -r '.datanet' "$f")"
      [[ "$datanet" =~ $id ]] || return 1
      printf 'mint-pod --datanet %s' "$datanet" ;;
    vote)
      local pod dir votes flag
      pod="$(jq -r '.pod' "$f")"
      dir="$(jq -r '.direction' "$f")"
      votes="$(jq -r '.votes // 1' "$f")"
      [[ "$pod" =~ $id ]] || return 1
      [[ "$votes" =~ ^[1-9][0-9]*$ ]] || return 1
      case "$dir" in
        like) flag="--like" ;;
        dislike) flag="--dislike" ;;
        *) return 1 ;;
      esac
      printf 'vote --pod %s --votes %s %s' "$pod" "$votes" "$flag" ;;
    *) return 1 ;;
  esac
}

for intent in "$PENDING_DIR"/*.json; do
  [ -f "$intent" ] || continue
  base="$(basename "$intent")"
  key="$(jq -r '.idempotency_key // empty' "$intent")"
  if [ -z "$key" ]; then
    echo "- \`$base\` — **skipped**: missing idempotency_key" >> "$RESULTS_FILE"
    rm -f "$intent"
    continue
  fi
  args="$(build_args "$intent")" || {
    echo "- \`$base\` — **skipped**: unknown command or invalid fields" >> "$RESULTS_FILE"
    rm -f "$intent"
    continue
  }

  # Dry-run preflight.
  echo "reppo-postprocess: dry-run $base..."
  if ! REPPO_NETWORK=mainnet reppo $args --idempotency-key "$key" --dry-run --json \
       > ".reppo-cache/dryrun-$base" 2>&1; then
    code="$(jq -r '.code // "UNKNOWN"' ".reppo-cache/dryrun-$base" 2>/dev/null || echo UNKNOWN)"
    echo "- \`$base\` — **dry-run failed** (code: $code), real write skipped" >> "$RESULTS_FILE"
    rm -f "$intent"
    continue
  fi

  if [ "$DRY_RUN_ONLY" = "true" ]; then
    echo "- \`$base\` — dry-run OK, real write skipped (REPPO_DRY_RUN_ONLY)" >> "$RESULTS_FILE"
    rm -f "$intent"
    continue
  fi

  # Real write.
  echo "reppo-postprocess: executing $base..."
  if REPPO_NETWORK=mainnet reppo $args --idempotency-key "$key" --json \
     > ".reppo-cache/result-$base" 2>&1; then
    tx="$(jq -r '.txHash // .transactionHash // "n/a"' ".reppo-cache/result-$base" 2>/dev/null || echo n/a)"
    echo "- \`$base\` — **success** (tx: $tx)" >> "$RESULTS_FILE"
  else
    code="$(jq -r '.code // "UNKNOWN"' ".reppo-cache/result-$base" 2>/dev/null || echo UNKNOWN)"
    echo "- \`$base\` — **write failed** (code: $code)" >> "$RESULTS_FILE"
  fi
  rm -f "$intent"
done

echo "reppo-postprocess: done"
