#!/usr/bin/env bash
# Post-process Reppo write intents left by Claude (sandbox blocks outbound network).
# Reads .pending-reppo/*.json, runs a --dry-run preflight, then the real write.
# Appends results to .outputs/reppo-trading-agent.md for the digest step.
#
# Env:
#   REPPO_PRIVATE_KEY     required for any write (script skips writes if unset)
#   REPPO_DRY_RUN_ONLY    if "true", run the dry-run preflight but skip real writes
set -euo pipefail

PENDING_DIR=".pending-reppo"
RESULTS_FILE=".outputs/reppo-trading-agent.md"
DRY_RUN_ONLY="${REPPO_DRY_RUN_ONLY:-false}"

if [ ! -d "$PENDING_DIR" ] || [ -z "$(ls -A "$PENDING_DIR"/*.json 2>/dev/null || true)" ]; then
  echo "reppo-postprocess: no pending intents"
  exit 0
fi

if [ -z "${REPPO_PRIVATE_KEY:-}" ]; then
  echo "reppo-postprocess: REPPO_PRIVATE_KEY not set, skipping all writes"
  mkdir -p .outputs
  {
    echo ""
    echo "## Execution Results"
    echo ""
    echo "_postprocess-reppo.sh skipped ALL writes: REPPO_PRIVATE_KEY is not set. No intents were executed on-chain._"
  } >> ".outputs/reppo-trading-agent.md"
  exit 0
fi

if ! command -v reppo >/dev/null 2>&1; then
  npm i -g @reppo/cli >/dev/null 2>&1 || {
    echo "reppo-postprocess: CLI missing"
    mkdir -p .outputs
    {
      echo ""
      echo "## Execution Results"
      echo ""
      echo "_postprocess-reppo.sh could not run: Reppo CLI unavailable. Pending intents were NOT executed._"
    } >> ".outputs/reppo-trading-agent.md"
    exit 0
  }
fi

mkdir -p .outputs .reppo-cache
{
  echo ""
  echo "## Execution Results"
  echo ""
  echo "_Generated by postprocess-reppo.sh ($(date -u +%FT%TZ)). dry_run_only=${DRY_RUN_ONLY}_"
  echo ""
} >> "$RESULTS_FILE"

# Build the CLI argument list for an intent file. Args: file. Echoes args.
# Returns 1 if the command is unknown or any field is malformed. Validating
# fields here keeps the later unquoted `$args` expansion safe (every word is
# then a controlled flag, an id token, or a positive integer — no spaces).
# `id` accepts Reppo's integer datanet/pod ids as well as hex/hyphenated ids.
build_args() {
  local f="$1" cmd id='^[A-Za-z0-9_-]+$'
  cmd="$(jq -r '.cmd' "$f")"
  case "$cmd" in
    mint-pod)
      local datanet
      datanet="$(jq -r '.datanet' "$f")"
      [[ "$datanet" =~ $id ]] || return 1
      printf 'mint-pod --datanet %s' "$datanet" ;;
    vote)
      local pod dir votes flag
      pod="$(jq -r '.pod' "$f")"
      dir="$(jq -r '.direction' "$f")"
      votes="$(jq -r '.votes // 1' "$f")"
      [[ "$pod" =~ $id ]] || return 1
      [[ "$votes" =~ ^[1-9][0-9]*$ ]] || return 1
      case "$dir" in
        like) flag="--like" ;;
        dislike) flag="--dislike" ;;
        *) return 1 ;;
      esac
      printf 'vote --pod %s --votes %s %s' "$pod" "$votes" "$flag" ;;
    *) return 1 ;;
  esac
}

# Helper: extract a structured error code from a reppo CLI JSON failure response.
# Returns .error.code (Reppo's standard error shape), or .code (legacy), or "UNKNOWN".
extract_code() {
  jq -r '.error.code // .code // "UNKNOWN"' "$1" 2>/dev/null || echo UNKNOWN
}

# Helper: extract a single-line, <=300-char detail from a captured CLI output file.
# Whitespace runs collapse to a single space so the result fits on one Markdown bullet.
extract_detail() {
  tr -s '[:space:]' ' ' < "$1" 2>/dev/null | cut -c1-300 || true
}

# Helper: pin a dataset file to IPFS via Pinata. Returns 0 with the CID
# echoed on stdout, 1 on failure (raw Pinata response captured in
# $2 for caller diagnostics). Pinata URL:
#   POST https://api.pinata.cloud/pinning/pinFileToIPFS
#   Authorization: Bearer $PINATA_JWT
#   multipart: file=@<path> + pinataMetadata
# Response: {"IpfsHash":"Qm…","PinSize":<int>,"Timestamp":"…"}
#
# Caller is responsible for checking PINATA_JWT is set before calling.
# The CID is a CIDv0 (Qm…) or CIDv1 (bafy…); we don't validate further,
# the gateway will. Caller wires the CID into the platform POST as
# https://ipfs.io/ipfs/<CID> — public-gateway URL, not Pinata's, so the
# pin is verifiable from any IPFS gateway (Pinata's role here is just
# pinning, not gating retrieval).
pin_dataset_to_ipfs() {
  local file="$1" capture="$2" name
  name="$(basename "$file")"
  if ! curl -fsS \
       -X POST "https://api.pinata.cloud/pinning/pinFileToIPFS" \
       -H "Authorization: Bearer ${PINATA_JWT}" \
       -F "file=@${file}" \
       -F "pinataMetadata={\"name\":\"${name}\"}" \
       > "$capture" 2>&1; then
    return 1
  fi
  local cid
  cid="$(jq -r '.IpfsHash // empty' "$capture" 2>/dev/null)"
  if [ -z "$cid" ] || [ "$cid" = "null" ]; then
    return 1
  fi
  echo "$cid"
}

# Helper: run a dry-run for the current intent. Retries up to 3 attempts on
# transient RPC failures (INTERNAL_ERROR / TIMEOUT / RATE_LIMITED /
# NETWORK_ERROR) with linear backoff. Relies on caller-scope $args / $key /
# $base. Returns 0 on success, 1 on terminal failure (last attempt's code
# remains in .reppo-cache/dryrun-$base for the caller to inspect).
dryrun_with_retry() {
  local attempt=1 code wait
  while : ; do
    if REPPO_NETWORK=mainnet reppo $args --idempotency-key "$key" --dry-run --json \
         > ".reppo-cache/dryrun-$base" 2>&1; then
      return 0
    fi
    code="$(extract_code ".reppo-cache/dryrun-$base")"
    case "$code" in
      INTERNAL_ERROR|TIMEOUT|RATE_LIMITED|NETWORK_ERROR)
        if [ "$attempt" -ge 3 ]; then return 1; fi
        wait=$((attempt * 5))
        echo "reppo-postprocess: transient $code on $base, retry in ${wait}s (attempt $attempt/3)" >&2
        sleep "$wait"
        attempt=$((attempt + 1))
        ;;
      *) return 1 ;;
    esac
  done
}

# Helper: try grant-access. On INSUFFICIENT_ALLOWANCE, auto-approve REPPO
# spend to the SubnetManager via `reppo approve` (CLI v0.5+) and retry
# grant-access. Returns 0 on grant success, 1 on terminal failure (final
# grant response remains in .reppo-cache/grant-$target.json for the caller
# to inspect).
auto_recover_grant() {
  local target="$1" gcode adetail approve_tx
  if REPPO_NETWORK=mainnet reppo grant-access --datanet "$target" --json \
       > ".reppo-cache/grant-$target.json" 2>&1; then
    return 0
  fi
  gcode="$(extract_code ".reppo-cache/grant-$target.json")"
  if [ "$gcode" != "INSUFFICIENT_ALLOWANCE" ]; then
    return 1  # not a recoverable failure; caller reports it
  fi

  # CLI v0.5+ ships `reppo approve` with built-in `subnet-manager` /
  # `reppo` aliases — it resolves spender + token internally, so we don't
  # need to know addresses, install foundry, or probe the SubnetManager ABI.
  # `--amount max` issues a MAX_UINT256 allowance (one-time, never re-approve).
  echo "reppo-postprocess: approving REPPO spend to subnet-manager (max)..." >&2
  if ! REPPO_NETWORK=mainnet reppo approve \
         --spender subnet-manager \
         --token reppo \
         --amount max \
         --idempotency-key "aeon-approve-subnet-manager-reppo" \
         --json \
       > ".reppo-cache/approve-$target.json" 2>&1; then
    adetail="$(extract_detail ".reppo-cache/approve-$target.json")"
    echo "  - auto-approve FAILED: ${adetail:-<empty>}" >> "$RESULTS_FILE"
    return 1
  fi
  approve_tx="$(jq -r '.transactionHash // .txHash // "n/a"' ".reppo-cache/approve-$target.json" 2>/dev/null || echo n/a)"
  echo "  - auto-approved REPPO spend to subnet-manager (tx: $approve_tx)" >> "$RESULTS_FILE"

  # Retry grant-access with linear backoff. `reppo approve` returns a tx
  # hash but the allowance read by grant-access may lag — the tx is mined,
  # but the RPC node grant-access hits may not have propagated the new
  # block yet (eventual-consistency on load-balanced RPC pools, observed
  # in the 15th reppo-swarm run: approve landed at tx 0xa7053dc4…,
  # immediate grant-access still read 0 allowance). Total wait: 5+10+15
  # = 30s (~15 Base blocks of headroom). Break early if a non-allowance
  # error appears — that's not a propagation race.
  local wait_attempt grant_code
  for wait_attempt in 1 2 3; do
    sleep "$((wait_attempt * 5))"
    if REPPO_NETWORK=mainnet reppo grant-access --datanet "$target" --json \
         > ".reppo-cache/grant-$target.json" 2>&1; then
      return 0
    fi
    grant_code="$(extract_code ".reppo-cache/grant-$target.json")"
    [ "$grant_code" = "INSUFFICIENT_ALLOWANCE" ] || break
  done
  return 1
}

# Helper: auto-approve REPPO spend to the PodManager via `reppo approve`
# (CLI v0.5+). Mirrors auto_recover_grant but for the mint-pod path —
# PodManagerV2.mintPodWithREPPO does
#   reppo.safeTransferFrom(msg.sender, address(this), publishingFee);
# so the spender that needs allowance is PodManager (proxy
# 0x5C563f853eb4db33005A5C1aD9290e8560254A80 on Base mainnet), NOT
# SubnetManager. subnet-manager and pod-manager are independent
# allowances — grant-access pulls REPPO via SubnetManager, mint-pod
# pulls REPPO via PodManager. A chain that does both needs both set.
# Returns 0 on approve success, 1 on terminal failure.
auto_recover_mint_allowance() {
  local adetail approve_tx
  echo "reppo-postprocess: approving REPPO spend to pod-manager (max)..." >&2
  if ! REPPO_NETWORK=mainnet reppo approve \
         --spender pod-manager \
         --token reppo \
         --amount max \
         --idempotency-key "aeon-approve-pod-manager-reppo" \
         --json \
       > ".reppo-cache/approve-pod-manager.json" 2>&1; then
    adetail="$(extract_detail ".reppo-cache/approve-pod-manager.json")"
    echo "  - auto-approve (pod-manager) FAILED: ${adetail:-<empty>}" >> "$RESULTS_FILE"
    return 1
  fi
  approve_tx="$(jq -r '.transactionHash // .txHash // "n/a"' ".reppo-cache/approve-pod-manager.json" 2>/dev/null || echo n/a)"
  echo "  - auto-approved REPPO spend to pod-manager (tx: $approve_tx)" >> "$RESULTS_FILE"
  # Brief sleep so the next dry-run's eth_call lands on a node that's
  # seen the receipt (same propagation race documented in
  # auto_recover_grant). dryrun_with_retry already has its own backoff
  # for INTERNAL_ERROR, but the allowance read can return stale 0 on
  # the first attempt without surfacing as a retriable code.
  sleep 5
  return 0
}

# Helper: auto-lock REPPO into veREPPO to give the publisher voting
# power. Mirrors auto_recover_grant / auto_recover_mint_allowance for
# the vote path — veREPPO.lock(amount, duration) is what `reppo lock`
# wraps. A wallet with 0 locked REPPO has 0 voting power, so every
# vote intent reverts with INSUFFICIENT_VOTING_POWER.
#
# Locks 500 REPPO for 30 days (~2592000s). Two CLI calls:
#  1. Approve ve-reppo to spend REPPO (the CLI may auto-approve
#     internally on `lock`, but doing it explicitly is cheaper than
#     failing the lock tx and recovering). Idempotency-keyed once
#     forever — no-ops on every subsequent invocation.
#  2. `reppo lock 500 --duration 2592000`. Idempotency-key is
#     date-stamped to the lock cycle (year-month), so attempts within
#     the same 30-day window no-op (CLI rejects duplicate key), but a
#     fresh month broadcasts a new lock — automatically refreshing
#     voting power if a prior lockup has matured.
#
# Returns 0 on lock success, 1 on terminal failure (operator must
# inspect: most likely cause is REPPO balance < 500).
auto_recover_lock() {
  local approve_tx lock_tx ldetail adetail amount=500 duration=2592000
  local approve_key="aeon-approve-ve-reppo-reppo"
  local lock_key="aeon-lock-$(date -u +%Y-%m)-${amount}-reppo-${duration}s"

  echo "reppo-postprocess: ensuring REPPO allowance to ve-reppo..." >&2
  if ! REPPO_NETWORK=mainnet reppo approve \
         --spender ve-reppo \
         --token reppo \
         --amount max \
         --idempotency-key "$approve_key" \
         --json \
       > ".reppo-cache/approve-ve-reppo.json" 2>&1; then
    adetail="$(extract_detail ".reppo-cache/approve-ve-reppo.json")"
    echo "  - auto-approve (ve-reppo) FAILED: ${adetail:-<empty>}" >> "$RESULTS_FILE"
    return 1
  fi
  approve_tx="$(jq -r '.transactionHash // .txHash // "n/a"' ".reppo-cache/approve-ve-reppo.json" 2>/dev/null || echo n/a)"
  if [ "$approve_tx" != "n/a" ]; then
    echo "  - auto-approved REPPO spend to ve-reppo (tx: $approve_tx)" >> "$RESULTS_FILE"
  fi

  echo "reppo-postprocess: locking ${amount} REPPO into veREPPO for ${duration}s (~30d)..." >&2
  if ! REPPO_NETWORK=mainnet reppo lock "$amount" \
         --duration "$duration" \
         --idempotency-key "$lock_key" \
         --json \
       > ".reppo-cache/lock.json" 2>&1; then
    ldetail="$(extract_detail ".reppo-cache/lock.json")"
    echo "  - auto-lock (${amount} REPPO, 30d) FAILED: ${ldetail:-<empty>}" >> "$RESULTS_FILE"
    return 1
  fi
  lock_tx="$(jq -r '.transactionHash // .txHash // "n/a"' ".reppo-cache/lock.json" 2>/dev/null || echo n/a)"
  echo "  - auto-locked ${amount} REPPO into veREPPO for 30d (tx: $lock_tx)" >> "$RESULTS_FILE"
  # Voting-power read can lag the lock tx receipt — same propagation
  # race as the allowance reads. dryrun_with_retry's backoff doesn't
  # cover INSUFFICIENT_VOTING_POWER (not in its retriable code set),
  # so absorb the lag with an explicit sleep before returning.
  sleep 5
  return 0
}

for intent in "$PENDING_DIR"/*.json; do
  [ -f "$intent" ] || continue
  base="$(basename "$intent")"
  key="$(jq -r '.idempotency_key // empty' "$intent")"
  if [ -z "$key" ]; then
    echo "- \`$base\` — **skipped**: missing idempotency_key" >> "$RESULTS_FILE"
    rm -f "$intent"
    continue
  fi
  args="$(build_args "$intent")" || {
    echo "- \`$base\` — **skipped**: unknown command or invalid fields" >> "$RESULTS_FILE"
    rm -f "$intent"
    continue
  }

  # Dry-run preflight. On a mint-pod failure with PUBLISHER_LACKS_SUBNET_ACCESS,
  # auto-grant datanet access and retry once. Gated on DRY_RUN_ONLY because
  # grant-access costs a real fee — Phase 0 stays free, real mode self-heals.
  echo "reppo-postprocess: dry-run $base..."
  if ! dryrun_with_retry; then
    code="$(extract_code ".reppo-cache/dryrun-$base")"
    detail="$(extract_detail ".reppo-cache/dryrun-$base")"
    cmd_name="$(jq -r '.cmd' "$intent")"

    if [ "$code" = "PUBLISHER_LACKS_SUBNET_ACCESS" ] && [ "$cmd_name" = "mint-pod" ] && [ "$DRY_RUN_ONLY" != "true" ]; then
      target="$(jq -r '.datanet' "$intent")"
      echo "reppo-postprocess: $base needs datanet access; auto-granting datanet $target..." >&2
      if auto_recover_grant "$target"; then
        grant_tx="$(jq -r '.txHash // .transactionHash // "n/a"' ".reppo-cache/grant-$target.json" 2>/dev/null || echo n/a)"
        echo "  - auto-granted datanet $target access (tx: $grant_tx)" >> "$RESULTS_FILE"
        # Retry the dry-run now that access is granted.
        if ! dryrun_with_retry; then
          code="$(extract_code ".reppo-cache/dryrun-$base")"
          detail="$(extract_detail ".reppo-cache/dryrun-$base")"
          echo "- \`$base\` — **dry-run failed after grant** (code: $code), real write skipped" >> "$RESULTS_FILE"
          echo "  - output: ${detail:-<empty>}" >> "$RESULTS_FILE"
          rm -f "$intent"
          continue
        fi
        # Retry passed — fall through to the dry-run-OK / real-write logic below.
      else
        gcode="$(extract_code ".reppo-cache/grant-$target.json")"
        gdetail="$(extract_detail ".reppo-cache/grant-$target.json")"
        echo "- \`$base\` — **dry-run failed** (code: $code) and auto-grant for datanet $target failed (code: $gcode), real write skipped" >> "$RESULTS_FILE"
        echo "  - output: ${detail:-<empty>}" >> "$RESULTS_FILE"
        echo "  - grant output: ${gdetail:-<empty>}" >> "$RESULTS_FILE"
        rm -f "$intent"
        continue
      fi
    elif [ "$cmd_name" = "mint-pod" ] && [ "$DRY_RUN_ONLY" != "true" ] \
         && grep -qiE '0x13be252b|InsufficientAllowance' ".reppo-cache/dryrun-$base"; then
      # Mint dry-run reverted with selector 0x13be252b (InsufficientAllowance,
      # no args — a hand-rolled custom error from the REPPO token's
      # transferFrom check). PodManagerV2.mintPodWithREPPO is the actual
      # spender (it does safeTransferFrom from itself, not via
      # SubnetManager), so subnet-manager allowance doesn't cover this —
      # pod-manager needs its own allowance. Approve and retry the
      # dry-run. The CLI surfaces this as code "UNKNOWN_REVERT_0x13be252b"
      # plus the selector in the hint message; the grep matches both the
      # selector and (defensively) the decoded name in case a future CLI
      # decodes it.
      echo "reppo-postprocess: $base hit InsufficientAllowance on PodManager; auto-approving pod-manager..." >&2
      if auto_recover_mint_allowance; then
        if ! dryrun_with_retry; then
          code="$(extract_code ".reppo-cache/dryrun-$base")"
          detail="$(extract_detail ".reppo-cache/dryrun-$base")"
          echo "- \`$base\` — **dry-run failed after pod-manager approve** (code: $code), real write skipped" >> "$RESULTS_FILE"
          echo "  - output: ${detail:-<empty>}" >> "$RESULTS_FILE"
          rm -f "$intent"
          continue
        fi
        # Retry passed — fall through to the dry-run-OK / real-write logic below.
      else
        echo "- \`$base\` — **dry-run failed** (code: $code) and auto-approve for pod-manager failed, real write skipped" >> "$RESULTS_FILE"
        echo "  - output: ${detail:-<empty>}" >> "$RESULTS_FILE"
        rm -f "$intent"
        continue
      fi
    elif [ "$cmd_name" = "vote" ] && [ "$code" = "INSUFFICIENT_VOTING_POWER" ] && [ "$DRY_RUN_ONLY" != "true" ]; then
      # Vote dry-run reverted because the publisher has 0 (or insufficient)
      # voting power on veREPPO. Auto-lock 500 REPPO for 30 days (the
      # standard cycle), then retry the dry-run. The lock is durable on
      # chain — subsequent runs within the 30-day window hit the
      # steady-state path (vote dry-run succeeds on the first call;
      # this branch never fires).
      echo "reppo-postprocess: $base hit INSUFFICIENT_VOTING_POWER; auto-locking 500 REPPO for 30d..." >&2
      if auto_recover_lock; then
        # Voting-power read can lag the lock tx receipt by 5-30s on
        # the load-balanced public Base RPC pool (eventual
        # consistency). Mirror auto_recover_grant's 5/10/15s = 30s
        # backoff before giving up. Break early on non-voting-power
        # errors (those aren't propagation races; extra waits won't
        # help). Observed in run 19: vote-372 dry-run failed at the
        # 5s post-lock mark from auto_recover_lock's internal sleep,
        # but vote-373 (processed ~10s later by the next loop
        # iteration) cleared on its first attempt — confirming
        # propagation completes in the 10-30s window for this race.
        local vote_wait vote_code dryrun_passed=false
        for vote_wait in 1 2 3; do
          sleep "$((vote_wait * 5))"
          if dryrun_with_retry; then dryrun_passed=true; break; fi
          vote_code="$(extract_code ".reppo-cache/dryrun-$base")"
          [ "$vote_code" = "INSUFFICIENT_VOTING_POWER" ] || break
        done
        if [ "$dryrun_passed" != "true" ]; then
          code="$(extract_code ".reppo-cache/dryrun-$base")"
          detail="$(extract_detail ".reppo-cache/dryrun-$base")"
          echo "- \`$base\` — **dry-run failed after lock (3 attempts)** (code: $code), real write skipped" >> "$RESULTS_FILE"
          echo "  - output: ${detail:-<empty>}" >> "$RESULTS_FILE"
          rm -f "$intent"
          continue
        fi
        # Retry passed — fall through to the dry-run-OK / real-write logic below.
      else
        echo "- \`$base\` — **dry-run failed** (code: $code) and auto-lock failed, real write skipped" >> "$RESULTS_FILE"
        echo "  - output: ${detail:-<empty>}" >> "$RESULTS_FILE"
        rm -f "$intent"
        continue
      fi
    else
      echo "- \`$base\` — **dry-run failed** (code: $code), real write skipped" >> "$RESULTS_FILE"
      echo "  - output: ${detail:-<empty>}" >> "$RESULTS_FILE"
      echo "reppo-postprocess: dry-run failed for $base: ${detail:-<empty>}" >&2
      rm -f "$intent"
      continue
    fi
  fi

  if [ "$DRY_RUN_ONLY" = "true" ]; then
    echo "- \`$base\` — dry-run OK, real write skipped (REPPO_DRY_RUN_ONLY)" >> "$RESULTS_FILE"
    rm -f "$intent"
    continue
  fi

  # Real write.
  cmd_name="$(jq -r '.cmd' "$intent")"
  echo "reppo-postprocess: executing $base..."
  if REPPO_NETWORK=mainnet reppo $args --idempotency-key "$key" --json \
     > ".reppo-cache/result-$base" 2>&1; then
    tx="$(jq -r '.txHash // .transactionHash // "n/a"' ".reppo-cache/result-$base" 2>/dev/null || echo n/a)"
    echo "- \`$base\` — **success** (tx: $tx)" >> "$RESULTS_FILE"

    # Phase-2 queue: for mint-pod, the on-chain tx creates the ERC-721
    # token but the Reppo UI surfaces pods from a platform DB row
    # populated by a separate authenticated POST. Queue the metadata
    # for the phase-2 loop below to drain. Decoupled from the on-chain
    # write so a failed POST never re-broadcasts the mint, and a
    # crashed run leaves the queue file in place for the next run.
    if [ "$cmd_name" = "mint-pod" ] && [ "$tx" != "n/a" ]; then
      mkdir -p .pending-reppo-register
      jq -n \
        --arg tx       "$tx" \
        --arg subnet   "$(jq -r '.datanet' "$intent")" \
        --arg name     "$(jq -r '.pod_name // .strategy_summary // "Aeon-generated pod"' "$intent")" \
        --arg desc     "$(jq -r '.pod_description // .strategy_summary // ""' "$intent")" \
        --arg url      "$(jq -r '.url // ""' "$intent")" \
        --arg dpath    "$(jq -r '.dataset_path // ""' "$intent")" \
        '{txHash:$tx,
          subnetId:($subnet|tonumber),
          podName:$name,
          podDescription:$desc,
          url:$url,
          platform:"Aeon",
          category:"Trading Strategy",
          agreeToTerms:true,
          imageURL:"",
          thumbnailURL:"",
          pdfURL:"",
          videoURL:"",
          dataset_path:$dpath,
          dataset_uri:""}' \
        > ".pending-reppo-register/${base}"
    fi
  else
    code="$(extract_code ".reppo-cache/result-$base")"
    detail="$(extract_detail ".reppo-cache/result-$base")"
    echo "- \`$base\` — **write failed** (code: $code)" >> "$RESULTS_FILE"
    echo "  - output: ${detail:-<empty>}" >> "$RESULTS_FILE"
    echo "reppo-postprocess: write failed for $base: ${detail:-<empty>}" >&2
  fi
  rm -f "$intent"
done

# --- Phase 2: register pod metadata to the Reppo platform DB ---
# The on-chain mintPodWithREPPO(to, subnetId) call creates the ERC-721
# token but doesn't carry any text/URI. The Reppo UI populates pod
# pages from a platform DB row created by:
#
#   POST https://reppo.ai/api/v1/agents/{AGENT_ID}/pods
#   Authorization: Bearer {AGENT_API_KEY}
#   { txHash, subnetId, podName, podDescription, url, platform,
#     category, agreeToTerms, image/thumbnail/pdf/videoURL }
#
# Bootstrap (one-time, operator runs locally):
#   REPPO_NETWORK=mainnet reppo register-agent --name "Aeon ..."
#   → returns {agentId, apiKey}; set as GH secrets
#     REPPO_AGENT_ID + REPPO_API_KEY.
#
# Failure mode: if either secret is missing OR the curl fails, we
# leave the queue file in place so the next chain run retries. The
# on-chain tx is durable; only the platform metadata POST is at risk
# of the transient.
REGISTER_DIR=".pending-reppo-register"
if [ -d "$REGISTER_DIR" ] && [ -n "$(ls -A "$REGISTER_DIR"/*.json 2>/dev/null || true)" ]; then
  if [ -z "${REPPO_AGENT_ID:-}" ] || [ -z "${REPPO_API_KEY:-}" ]; then
    echo "reppo-postprocess: REPPO_AGENT_ID or REPPO_API_KEY not set; phase-2 register skipped (queue files retained for next run)" >&2
    {
      echo ""
      echo "_Phase 2 (Reppo platform metadata POST) skipped: REPPO_AGENT_ID / REPPO_API_KEY missing. $(ls "$REGISTER_DIR" | wc -l | tr -d ' ') pending file(s) retained for next run._"
    } >> "$RESULTS_FILE"
  else
    {
      echo ""
      echo "**Phase 2 — Reppo platform metadata POST:**"
    } >> "$RESULTS_FILE"
    for register_intent in "$REGISTER_DIR"/*.json; do
      [ -f "$register_intent" ] || continue
      rbase="$(basename "$register_intent")"
      rtx="$(jq -r '.txHash' "$register_intent" 2>/dev/null || echo n/a)"
      dpath="$(jq -r '.dataset_path // ""' "$register_intent" 2>/dev/null || echo "")"
      duri="$(jq -r '.dataset_uri // ""' "$register_intent" 2>/dev/null || echo "")"

      # Step 2a: pin the dataset to IPFS (Pinata) if there is one, the
      # CID isn't already recorded, and PINATA_JWT is configured. The
      # CID gets persisted into the queue file so a later POST retry
      # (after a transient platform-API failure) doesn't re-upload.
      if [ -n "$dpath" ] && [ -z "$duri" ] && [ -n "${PINATA_JWT:-}" ] && [ -f "$dpath" ]; then
        echo "reppo-postprocess: pinning $dpath to IPFS for $rbase..." >&2
        if cid="$(pin_dataset_to_ipfs "$dpath" ".reppo-cache/pinata-$rbase.json")"; then
          duri="https://ipfs.io/ipfs/${cid}"
          # Atomic patch: rewrite the queue file with dataset_uri set.
          tmp="$(mktemp)"
          jq --arg uri "$duri" '.dataset_uri = $uri' "$register_intent" > "$tmp" \
            && mv "$tmp" "$register_intent"
          echo "  - dataset pinned: ipfs://${cid} (gateway: $duri)" >> "$RESULTS_FILE"
        else
          pdetail="$(extract_detail ".reppo-cache/pinata-$rbase.json")"
          echo "- \`$rbase\` — **IPFS pin failed**: ${pdetail:-<empty>} (queue file retained for retry)" >> "$RESULTS_FILE"
          echo "reppo-postprocess: pinata pin failed for $rbase: ${pdetail:-<empty>}" >&2
          # Leave file for retry. Skip the POST this run.
          continue
        fi
      elif [ -n "$dpath" ] && [ -z "$duri" ] && [ -z "${PINATA_JWT:-}" ]; then
        # Dataset exists but PINATA_JWT not set — POST without dataset_uri.
        # Operator can backfill the pin later by setting the secret.
        echo "  - PINATA_JWT not set; POST proceeds without IPFS dataset link" >> "$RESULTS_FILE"
      fi

      # Step 2b: project queue body to the platform schema. Strip our
      # internal fields (dataset_path, dataset_uri) and map dataset_uri
      # into pdfURL — the platform schema's downloadable-file slot.
      # This way the queue file carries our bookkeeping while the wire
      # body only carries the platform's expected keys.
      body_file=".reppo-cache/post-body-$rbase"
      jq '{txHash, subnetId, podName, podDescription, url, platform,
           category, agreeToTerms, imageURL, thumbnailURL,
           pdfURL: (.dataset_uri // .pdfURL // ""),
           videoURL}' \
        "$register_intent" > "$body_file"

      echo "reppo-postprocess: registering metadata for $rbase (tx $rtx)..." >&2
      if curl -fsS -X POST "https://reppo.ai/api/v1/agents/${REPPO_AGENT_ID}/pods" \
           -H "Authorization: Bearer ${REPPO_API_KEY}" \
           -H "Content-Type: application/json" \
           --data @"$body_file" \
           > ".reppo-cache/register-$rbase" 2>&1; then
        if [ -n "$duri" ]; then
          echo "- \`$rbase\` — **metadata registered** (tx: $rtx, dataset: $duri)" >> "$RESULTS_FILE"
        else
          echo "- \`$rbase\` — **metadata registered** (tx: $rtx)" >> "$RESULTS_FILE"
        fi
        rm -f "$register_intent"
        # The local dataset file is now durably pinned on IPFS (or
        # there wasn't one). Drop it so it doesn't accumulate in the
        # auto-commit and so a future run's hash-dedup is the only
        # signal needed to skip re-minting.
        [ -n "$dpath" ] && rm -f "$dpath"
      else
        rdetail="$(extract_detail ".reppo-cache/register-$rbase")"
        echo "- \`$rbase\` — **metadata registration failed**: ${rdetail:-<empty>}" >> "$RESULTS_FILE"
        echo "reppo-postprocess: register failed for $rbase: ${rdetail:-<empty>}" >&2
        # Leave queue + dataset files for retry. CID is already pinned
        # and persisted into the queue file so retry won't re-upload.
      fi
    done
  fi
fi

echo "reppo-postprocess: done"
